### ISSUE TITLE
vkbasalt smaa looks worse than the smaa that's build into the game

### ISSUE THREAD

**Issue by Toadfield** [DadSchoorse/vkBasalt#107]
I tested Prey 2017 once with vkbasalt and once without,but with the smaax2 that's build into the game,the strange thing is that the build in smaa looks better for some reason.
My settings:https://i.imgur.com/eiv8FJu.png
The game with vkbasalt:https://i.imgur.com/agfy4Tm.jpg
The game with it's build in smaa x2:https://i.imgur.com/ErL4hvL.jpg
I expected that the vkbasalt smaa will look much better than the one that's build into the game,so did I forget something in my settings that makes it look much better or is it not possible to make it look better?

**Comment by DadSchoorse** [comment]
> I expected that the vkbasalt smaa will look much better than the one that's build into the game

Well, I don't know why you expected that, vkBasalt's AA is meant to be used in games without (or with bad) anti-aliasing. Especially against higher quality SMAA modes, which the game uses. vkBasalt can only use the most basic SMAA because there's no way to get multi-sampling, jittering or motion vectors.

**Comment by Toadfield** [comment]
@DadSchoorse Oh that's the reason,I wasn't thinking about,that the games smaa isn't limited to post processing.

**Comment by Toadfield** [comment]
@Calinou Thanks,but I can't find it in the q&a.

**Comment by Calinou** [comment]
@Toadfield The pull request hasn't been merged yet :slightly_smiling_face:
