### ISSUE TITLE
Can't set individual config for Steam games

### ISSUE THREAD

**Issue by MightyBalls6** [DadSchoorse/vkBasalt#167]
vkBasalt seems to function correctly on Proton 6.14+, for me at least, but it always pulls the global config. I'd like to set it per-game. `VKBASALT_CONFIG_FILE=/path/to/vkBasalt.conf` doesn't work, game working directory doesn't work either. Wine games work as expected, it's only an issue with Proton.

**Comment by GoGoOtaku** [comment]
Using `VKBASALT_CONFIG_FILE` environment variable works for me. You have to use absolute paths tho. `~` and `$HOME` don't work. I am unsure if this is due to proton/wine or steam runtime/pressure-vessel. Since this should be resolved before the variable is set I don't think this is a vkBasalt issue.

**Comment by MightyBalls6** [comment]
Absolute paths were used. You're right that it was a Steam Runtime/Pressure-vessel issue, not sure what it was or why, as I never messed with it and everything else was fine. But simply reinstalling worked.

Cheers.
