### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by John-Gee** [DadSchoorse/vkBasalt#17]
Please add a license to the project.
It will then be cleaner to package it by distributions.

**Comment by DadSchoorse** [comment]
Yes this is something I need to solve. I have not done it because I used https://github.com/baldurk/sample_layer and I don't know what to do with the 2-clause BSD-License.
Other than that I only used the CAS-Port: https://gist.github.com/martymcmodding/30304c4bffa6e2bd2eb59ff8bb09d135, but this is MIT-Licensed so this should not be a Problem.

**Comment by John-Gee** [comment]
I am not an expert on licenses so I will refrain from commenting on those :)

Thank you!

**Comment by serebit** [comment]
While I'm not an expert on licenses either, I'd use a license like Apache 2.0 or MIT, and retain the copyright notice on any files that came from baldurk's sample_layer, along with the copyright notice for the CAS port.

**Comment by DadSchoorse** [comment]
Should be fix by 4410e0ea5e8380f9274e7fa53b029e25e55f3408, this project is now licensed under the zlib-License.
