### ISSUE TITLE
0.3.2.8: fails to build with error: 'VK_LAYER_EXPORT' does not name a type

### ISSUE THREAD

**Issue by tgurr** [DadSchoorse/vkBasalt#207]
using
glslang: 12.0.0
vulkan: 1.3.241
```
FAILED: src/libvkbasalt.so.p/basalt.cpp.o 
x86_64-pc-linux-gnu-c++ -Isrc/libvkbasalt.so.p -Isrc -I../vkBasalt-0.3.2.8/src -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++2a -O0 -g -march=native -O2 -pipe -march=native -O2 -fPIC -MD -MQ src/libvkbasalt.so.p/basalt.cpp.o -MF src/libvkbasalt.so.p/basalt.cpp.o.d -o src/libvkbasalt.so.p/basalt.cpp.o -c ../vkBasalt-0.3.2.8/src/basalt.cpp
../vkBasalt-0.3.2.8/src/basalt.cpp:70:5: error: 'VK_LAYER_EXPORT' does not name a type
   70 |     VK_LAYER_EXPORT VkResult VKAPI_CALL vkBasalt_CreateInstance(const VkInstanceCreateInfo*  pCreateInfo,
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:136:5: error: 'VK_LAYER_EXPORT' does not name a type
  136 |     VK_LAYER_EXPORT void VKAPI_CALL vkBasalt_DestroyInstance(VkInstance instance, const VkAllocationCallbacks* pAllocator)
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:151:5: error: 'VK_LAYER_EXPORT' does not name a type
  151 |     VK_LAYER_EXPORT VkResult VKAPI_CALL vkBasalt_CreateDevice(VkPhysicalDevice             physicalDevice,
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:286:5: error: 'VK_LAYER_EXPORT' does not name a type
  286 |     VK_LAYER_EXPORT void VKAPI_CALL vkBasalt_DestroyDevice(VkDevice device, const VkAllocationCallbacks* pAllocator)
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:750:5: error: 'VK_LAYER_EXPORT' does not name a type
  750 |     VK_LAYER_EXPORT VkResult VKAPI_CALL vkBasalt_EnumerateInstanceLayerProperties(uint32_t* pPropertyCount, VkLayerProperties* pProperties)
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:766:5: error: 'VK_LAYER_EXPORT' does not name a type
  766 |     VK_LAYER_EXPORT VkResult VKAPI_CALL vkBasalt_EnumerateDeviceLayerProperties(VkPhysicalDevice   physicalDevice,
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:773:5: error: 'VK_LAYER_EXPORT' does not name a type
  773 |     VK_LAYER_EXPORT VkResult VKAPI_CALL vkBasalt_EnumerateInstanceExtensionProperties(const char*            pLayerName,
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:790:5: error: 'VK_LAYER_EXPORT' does not name a type
  790 |     VK_LAYER_EXPORT VkResult VKAPI_CALL vkBasalt_EnumerateDeviceExtensionProperties(VkPhysicalDevice       physicalDevice,
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:820:5: error: 'VK_LAYER_EXPORT' does not name a type
  820 |     VK_LAYER_EXPORT PFN_vkVoidFunction VKAPI_CALL vkBasalt_GetDeviceProcAddr(VkDevice device, const char* pName);
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:821:5: error: 'VK_LAYER_EXPORT' does not name a type
  821 |     VK_LAYER_EXPORT PFN_vkVoidFunction VKAPI_CALL vkBasalt_GetInstanceProcAddr(VkInstance instance, const char* pName);
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:860:5: error: 'VK_LAYER_EXPORT' does not name a type
  860 |     VK_LAYER_EXPORT PFN_vkVoidFunction VKAPI_CALL vkBasalt_GetDeviceProcAddr(VkDevice device, const char* pName)
      |     ^~~~~~~~~~~~~~~
../vkBasalt-0.3.2.8/src/basalt.cpp:875:5: error: 'VK_LAYER_EXPORT' does not name a type
  875 |     VK_LAYER_EXPORT PFN_vkVoidFunction VKAPI_CALL vkBasalt_GetInstanceProcAddr(VkInstance instance, const char* pName)
      |     ^~~~~~~~~~~~~~~
```
full build log: [vkbasalt-0.3.2.8.log.txt](https://github.com/DadSchoorse/vkBasalt/files/10828612/vkbasalt-0.3.2.8.log.txt)

**Comment by DadSchoorse** [comment]
Yeah looks like a poor Vulkan-Headers decision: https://github.com/KhronosGroup/Vulkan-Headers/commit/e8b8e06d092ab406b097907ecaae1a8aae9c7d53

I guess I'll have to tag another release just of this mess. In the meantime I think if you remove the `VK_LAYER_EXPORT` it should still work.

**Comment by juan-lunarg** [comment]
> Yeah looks like a poor Vulkan-Headers decision: https://github.com/KhronosGroup/Vulkan-Headers/commit/e8b8e06d092ab406b097907ecaae1a8aae9c7d53

I'd like to try and explain the rational.

1.) If you don't mark function as `extern "C"` you risk name mangling. This is true on all platforms.
2.) `vulkan/vk_layer.h` is an unofficial helper header file, so it's not part of the vulkan api. It's meant to assist layer developers write `cross-platform` code. `VK_LAYER_EXPORT` made writing cross-platform code more difficult since it didn't handle MSVC which is very weird conditional logic to have to handle in your build if you are caught unaware. I primarily work on linux so imagine my surprise when Windows builds didn't export my function. This is very annoying to debug.
3.) `__declspec(ddlexport)` will mangle 32 bit functions regardless of `extern "C"` meaning there was no way to maintain compatibility. The answer is to use `.def` files or use microsoft magic (https://stackoverflow.com/a/2805560/19739129)
4.) Layers are special plugin type libraries with a small list of needed export symbols. Meaning --version-script and .def files are preferable. In particular --version-script can actually reduce the size of your binary if absorbing 3rd-party code (like boost) which exports symbols unconditionally. This becomes a problem on large code bases when dealing with poorly written third party libraries.
5.) No good way to deprecate macros in a cross-platform manner. Because macros and msvc.
6.) Allows developers to re-evaluate what they are exporting from their layers. As an example: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/be666f39c462905ef245d88ff8f36bc8a8e7cf8e
7.) On GNU/Clang symbols aren't hidden by default so this macro is a no-op unless the user opts into it

Again I do realize this is an annoying change. But I did put quite a bit of thought into it. And we were able to improve various layers of the vulkan sdk after re-evaluating the functions we were exporting.
