### ISSUE TITLE
Need option for set destdir of shader files

### ISSUE THREAD

**Issue by tim77** [DadSchoorse/vkBasalt#25]
Now cas file installs into home dir, but we need option during build to set install prefix.

https://github.com/DadSchoorse/vkBasalt/blob/master/src/basalt.cpp#L34
std::string casFile = std::string(getenv("HOME")) + "/.local/share/vkBasalt/shader/cas.comp.spv";

**Comment by Calinou** [comment]
Speaking of which, the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) should be followed. This can be done like this (pseudocode):

```cpp
std::string casFile = std::string(getenv("XDG_DATA_HOME") || getenv("HOME") + "/.local/share") + "/vkBasalt/shader/cas.comp.spv";
```

**Comment by DadSchoorse** [comment]
So since 03b8c21ae1ecc4fc4817a787c6f77291fe886a16, there are 4 Options for the shader directory:
- a dir set with `VKBASALT_SHADER_PATH=/path/to/vkBasalt/shader` environment variable
- the old shader folder `$HOME/.local/share/vkBasalt/shader/` or `$XDG_DATA_HOME/vkBasalt/shader/`
- `/usr/share/vkBasalt/shader`
- `/usr/local/share/vkBasalt/shader`

Is that enough for your use case, or do still want the option to set it during build?

**Comment by tim77** [comment]
@DadSchoorse i would say this is enough for this case but there is still needed **many** things to do and improvements in makefile and build process and better track this in separate tickets. So closing now this. Thank you for continue to work on this project.

Note: for this who struggle after this update shader directory and using non default location - need to remove first `rm -r ~/.local/share/vkBasalt/shader`
