### ISSUE TITLE
fps limiter and vsync strategy

### ISSUE THREAD

**Issue by kokoko3k** [DadSchoorse/vkBasalt#36]
I know there are already 2 implementation of this.
One from the (seems abandoned) libstrangle, the other one via VkGHL,  but it would be nice to have it implemented right here.
Thanks!

**Comment by ionenwks** [comment]
Was just thinking about that myself a few minutes ago as I was looking at my vkcube spinning at 7000fps and some post-processing with
`VSYNC=0 FPS=7000 VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_VkGHL:VK_LAYER_VKBASALT_PostProcess  vkcube`
It'd make things simpler. 
(invocation is bit different because I setup my vkbasalt install system-wide with a rough gentoo ebuild, so now it's an explicit layer and it automatically gets the right 32/64 bit library with a single json file).

I still keep libstrangle for opengl though (works fine).

**Comment by kokoko3k** [comment]
Nice to hear!
Let me push you a bit further, it would be super if settings could be changed runtime; in particular for fps limiting (thinking about notebooks being disconnected from the mains, the fps could be lowered accordingly)

**Comment by DadSchoorse** [comment]
I don't see my I should implement this because VkGHL seems to work perfectly fine.

**Comment by jarrard** [comment]
VkGHL does not work that well and only for some things. Sorry.

**Comment by DadSchoorse** [comment]
@jarrard I still would like to not have this feature in **this** layer. vkBasalt is meant to be a post-processing layer. Writing a new one or maintaining VkGHL for FPS limits would be better.
