### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by oscarbg** [DadSchoorse/vkBasalt#61]
Hi,
I know we have Reshade and Nvidia Freestyle on Windows but still interested on testing VkBasalt on Windows for Intel GPUs..
any plans on supporting Windows?
thanks..

**Comment by DadSchoorse** [comment]
I'm not sure why you would want that, reshade is better in almost ever regard (gui, shader support, setup, ...).
Also the code does do some stuff linux specific so, no , sorry.

**Comment by CeeJayDK** [comment]
You're better off with Reshade for the foreseeable future.

VkBasalt is a new post processor, and it's going to take time to get all the features that Reshade has.

And until then there is no reason to focus on bringing VkBasalt to Windows, especially because Reshade already does Windows. It would be a better use of time to first ensure the experience on Linux is a great one. Only then does it make sense to look for new platforms to support.
One thing at a time.
