### ISSUE TITLE
Launching any game with ANY reshade effect enabled causes the game to just be a blank window and never fully launch

### ISSUE THREAD

**Issue by HankHill567** [DadSchoorse/vkBasalt#77]
The title says it all but basically whenever I launch a game with any of the reshade effects enabled the game just launches into a blank window thats looks like whatever was on my screen at the time. All of the basic shaders that come with vkBasalt like CAS and SMAA work.
Im also using a navi gpu specifically the rx 5700xt.

This is my file if that makes any difference because for all I know I might just be doing something wrong.
new screenshot of my configs: 
![Screenshot_20200416_161356](https://user-images.githubusercontent.com/63802373/79502227-5489ec80-7ffd-11ea-83bb-384564289503.png)

**Comment by nickgirga** [comment]
To my understanding, the # is a comment. That means that in your config all of your effects and the paths they point to have been commented out. When you start your game, it sees you have effects enabled, but it has no idea where to look because it can't see comments. I would try deleting all of the # symbols in front of the paths to your textures and effects.

`<blockquote class="imgur-embed-pub" lang="en" data-id="a/kvShHif"><a href="//imgur.com/a/kvShHif"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

*I have some comments in front of certain effects because I tried them and saw that they didn't work, so I disabled them.

**Comment by HankHill567** [comment]
Thanks for the help dude so my latter guess was right I am just stupid.
