### ISSUE TITLE
Problem with float parsing

### ISSUE THREAD

**Issue by John-Gee** [DadSchoorse/vkBasalt#93]
Hello,

apologies if I'm wrong but that reminded me of the other float parsing issues in 0.3.2 so I thought it might be related.

When I try to run colourfullness from reshade, following the example in the readme I get:

vkBasalt warn:  invalid float value for: colourfulness

I suppose the shader could be wrong, but it's straight from their github so others would have complained earlier I think.

Thanks!

**Comment by DadSchoorse** [comment]
This is actually not a bug, but a feature. Before 0.3.2 you would have gotten a hard crash :frog:.
It's caused by the shader having a setting also called `colourfulness` so vkBasalt tries to parse a float from the shader path.
Maybe I should rename `colourfulness` in the example in the README, the error message might confuse some people.

**Comment by John-Gee** [comment]
Oooooh I see, sorry for not checking the shader itself that might have been obvious :/

It'd be nice to rename in the example but also add why a workaround is needed.

I could do that tonight once I get some time if you want.

Thank you!
